### ISSUE TITLE
build_commit_history.py fails on line 78 for certain repos

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_dev#13]
I.e. `len(refs)!=len(parents)`.

When I use our mining scripts (e.g. `start.py` & `build_commit_history.py`) on certain OSH repositories, `build_commit_history.py` fails on line 78.

I'll post exactly which repository caused the problem plus more details  in my next comment in this issue thread.

**Comment by penyuan** [comment]
Noting the following observation before I forget:

The problem typically happens after a merge where a commit (i.e. the merge commit) has two parent commits. This causes `len(refs)!=len(parents)`.

**Comment by penyuan** [comment]
I will try a few tweaks to `build_commit_history.py` to make this work. Please stand by.

**Comment by penyuan** [comment]
This breakage is part of the code that tries to differentiate branches by color. In case this is not a trivial and quick fix. We can simply not color the branches for now.

**Comment by penyuan** [comment]
I've temporarily commented out colorisation until a fix for that function is implemented.

**Comment by jbon** [comment]
Issue fixed in b43b042 in branch `iss13`. Tested successfully for repositories `OPEN-NEXT/wp2.2_reference`, `OPEN-NEXT/wp2.2_dev` and `jbon/github-mining`.

**Comment by penyuan** [comment]
Just confirming that I'm looking at this. Thanks!

**Comment by penyuan** [comment]
Sorry, forgot to say that the changes have been merged into the `master` branch.

**Comment by jbon** [comment]
moved to #30
