### ISSUE TITLE
Allow passing in a list of repositories to mine

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_dev#19]
Currently our script allows specifying one GitHub repository to retrieve data from. Expand this to allow passing in a *list* of repositories to mine (related to issue #17).

Ideally, this list won't be limited to GitHub repositories, but we can start with accepting just GitHub repositories as a MVP (minimum viable product) for this issue.

**Comment by penyuan** [comment]
By the way, I think this issue is ideally tackled with issue #14 so that the list of repositories can be specified in a configuration file *or* commandline argument.

**Comment by penyuan** [comment]
Update: I am implementing this as part of working on issue #14 in the branch `iss14`. That branch is in progress so I won't merge it into master yet.

**Comment by penyuan** [comment]
Incorporated into solution for issue #14, and now merged into `master` branch. See if it works!

**Comment by jbon** [comment]
Tested without issue.

**Comment by penyuan** [comment]
Thanks.
