### ISSUE TITLE
Need place to put files/info related to process facilitation dashboard

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_dev#2]
I think there should be a place to aggregate information we have regarding the development of the process facilitation dashboard.

So far I can think of four candidates:

1. The TUB Cloud hosted by TU Berlin (in the appropriate folder)
2. The Wiki for this git repository
3. A directory containing Markdown and other files inside this git repository
4. A project hosted on [OSF.io](https://osf.io/), meaning if and when we choose to do so, we can easily publish our results there that includes a citable [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier)

I am slightly inclined toward option 3 because it can be version-controlled. Option 4 is also good but I recognise that it requires most of us to learn a new (albeit powerful) tool. Either way I am not super opinionated on this.

**Comment by chrvoigt** [comment]
+1 
option 3 and 4 seem good, I am not very informed about 'what information will go there' but then github pages is a nice way to present updates outside the github format https://pages.github.com/

**Comment by penyuan** [comment]
> but then github pages is a nice way to present updates outside the github format

Oh yeah I'd forgotten about Github Pages. One could, given enough ambition, set up automatic publishing to Github Pages.

Right now, I've got bits of Python source code in this repository. If we want to publish to Github Pages from this repository, would that conflict with the source code already hosted here? I.e., do we need a separate repository?

**Comment by chrvoigt** [comment]
I think it's for documentation of Repos, i.e. you can specify one specific folder that get's published e.g. /doc/ and the rest is not affected .. but yes it's all about 'ambition' :-D https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by penyuan** [comment]
Thanks @chrvoigt! I've managed to create a rudimentary test page [here](https://open-next.github.io/wp2.2_dev/).

**Comment by penyuan** [comment]
I've been able to put `*.md` files in the `docs` directory of this repository and so far no major problems. Will close this issue for now, but please raise new issues if and when they occur.
