### ISSUE TITLE
Generate interaction graphs based on file co-edition

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#23]

**Comment by penyuan** [comment]
Thanks so much. Yes, I will take a look at this branch and merge as appropriate. I've been working on issue #14 which will propagate some changes through other files in out repository, including this one.

**Comment by penyuan** [comment]
I see that this has been merged into the `vis-js` branch. I've tested it on the `wp2.2_dev` and `wp2.2_reference` repositories with not errors, and I can view the GraphML results in yEd.

I will close this issue and merge the changes in this issue and `vis-js` into the `master` branch.

**Comment by jbon** [comment]
ok i didn't expect you to to merge `vis-js` as well, but right, why not. I'll continue to commit on this branch though (as I just did).
