### ISSUE TITLE
Add bi-directionality in committer graphs

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#25]
so far we use a `networkx.Graph` what can only record one link between two nodes. As a result, we mix up interactions going from a committer to another and those going the other way round.

Alternative is to use a `networkx.MultiGraph` that allows parallel edges. This would be compatible with a vis.js visualisation. I couldn't tell from the networkx doc whether it is compatible with GraphML export, though. 

Alternatively an undirected graph with two weight attributes _from_ and _to_ would do the thing.

**Comment by jbon** [comment]
fixed in 3029d40a. From my side ready to review.
Merging this branch with `visjs` downstream cdaed196 related to #5 would generate visjs directed graph visualisations with parallel edges.

**Comment by penyuan** [comment]
Will test and merge as needed, thanks!! :)

**Comment by penyuan** [comment]
Merged into `master` branch.
