### ISSUE TITLE
use python fstrings instead of series of string.append in export_committer_graph

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#28]
https://realpython.com/python-f-strings/

**Comment by penyuan** [comment]
I have been trying to implement f strings elsewhere in the code, too. It looks more elegant to me, so I agree it might be good for us to do this.

**Comment by jbon** [comment]
I was planning to use this in the bit of code where I import `visjs_template.html` into a string,, insert graph data in this string and save the result in a new file. 

But it turns out you can't store a fstring in a variable, fstrings work only when you write them literally in the code. (see https://stackoverflow.com/questions/54351740/how-can-i-use-f-string-with-a-variable-not-with-a-string-literal)

An alternative would be to use `str.format` or `str.format_map` but this would require to excape all curly brackets in the string.

But this would require me to escape all curly brackets in the `visjs_template.html`. As such doable, but not practical for now to develop and debug the template itself. 

Conclusion: Won't fix
