### ISSUE TITLE
Document  how to use the script

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#31]

**Comment by jbon** [comment]
with `7bb316f ` I moved the contents of repolist_example.csv and config_example.json into documentation. I found it was not clean to have CSV and JSON files among source files. I created for this a new `manual.md` in `docs`.

**Comment by jbon** [comment]
Other things to do would be:

 - [ ] add information about installation
 - [ ] @penyuan clarify the version dependency created by perceval (I had in mind that perceval requires python <=3.6 but the perceval doc says >= 3.4)
 - [ ] @penyuan clarify why `--create_data_dir` does not have a short command line id (like `-r` for `repolist`)

**Comment by jbon** [comment]
@penyuan can you review and merge back to master the current state (`efc47343`) ? We can then let this issue open and continue working in this branch in parallel.

**Comment by penyuan** [comment]
Thanks I've merged the branch `iss31` up to and including commit efc47343 into the `master` branch.

**Comment by penyuan** [comment]
Oh, and for documentation, I think documentation *within* the script as doscstrings and comments are equally important. So for this issue, I will try to do that, too.

**Comment by penyuan** [comment]
This includes instructions for frontend, how to host backend and frontend, how to contribute, and at least basic description of architecture and how the code is set up. Remember to follow README standard(s).
