### ISSUE TITLE
Add event time stamps in committer graphs

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#34]
In order to analyse the chronoligical evolution of the committer graphs, we don't only need to know how much events two commiters have in common, we also need to know when each of these events happened. Doing so, we'll be able to filter the graph through a time window, instead of computing it for the whole time frame of the project. 

I think the best option is to first create the full graph over the entire project timeframe with some kind of list object (or maybe a pandas dataframe?) as attribute of each node. From this, with a filtering function, we would be able to prune the graph, excluding events outside a selected time window.

**Comment by jbon** [comment]
Actually it makes more sense to apply time stamp on the input data (e.g. list of commits fetched by perceval) so we can process filtered versions of it. 

This is the logic I implemented in 554d629: I put the commit data in a pandas.DataFrame we can arbitrarily filter by time window. That way, we can create different snapshots of all processed data (commit history, file change history, committer graph etc) over sliding windows and get a "flashback movie" of the project instead of a single view.

**Comment by penyuan** [comment]
Thanks. I merged `iss34` into `master`. Let me know if there are issues.

**Comment by penyuan** [comment]
Quick note that - based I what I've learned so far - including timestamps shouldn't be difficult even if we migrate to using the GitHub GraphQL API for pulling metadata.
