### ISSUE TITLE
generate dashboard design mockups

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#35]
a thread to track our discussions regarding dashboard designs

**Comment by penyuan** [comment]
With much thanks to @jbon, we've discussed the dashboard design mockups and came up with one for a month-18 (M18) minimum viable product (MVP), specifically [`M18.svg`](https://github.com/OPEN-NEXT/wp2.2_dev/blob/docs/docs/mockups/M18.svg) and [`selectedFeaturesM18.csv`](https://github.com/OPEN-NEXT/wp2.2_dev/blob/docs/docs/mockups/selectedFeaturesM18.csv) in [here](https://github.com/OPEN-NEXT/wp2.2_dev/tree/docs/docs/mockups).

I'll close this issue for now. Once we work on new design mockups for post-M18 iterations of the dashboard, we can open new issues that that time as needed.
