### ISSUE TITLE
Badges for dashboard

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_dev#39]
In recent meetings [such as this one on 2020-09-16](https://github.com/OPEN-NEXT/wp2.2_dev/blob/docs/docs/meeting-notes.md#inter-wp-wikibase-meeting-notes-2020-09-16t14000100), we discussed "achievement" badges that will be part of the Open!Next month-18 dashboard minimum viable product (MVP).

This issue is to discuss the badges and develop an initial list to be part of the month-18 MVP.

**There will be two kinds of badges:**

1. Self-awarded/declared - If you (as a repository/project owner) decide that you meet the criteria for a badge, you can tick a box indicating so yourself. Question: What would be the *technical* mechanism for creating and for the dashboard to *detect* self-awarded badges?

2. Automated badges - The backend of the dashboard will decide whether to award a badge on if the mined metadata meets certain criteria.

**One example of a badge implementation:**

As we know from gamification, there can be multiple levels of the same badge. @moedn suggested a [DIN SPEC 3105](https://gitlab.com/OSEGermany/OHS/-/blob/master/DIN_SPEC_3105_explained.md) badge. The three levels might be: 

1. Bronze - You self-declare that your project meets the DIN SPEC.
2. Silver - You self-declare you've started the certification process. (maybe this can be automated if the DIN SPEC application/certification process will produce metadata for the dashboard's backend to detect???)
3. Gold - Automatically awarded once DIN SPEC 3105 conformance is confirmed.

----------

Let's discuss the mechanisms for how the badge system will work *and* come up with an initial set of badges for the month-18 dashboard.

I'll try to post a few of my ideas soon, but please chime in with your thoughts on any of the above at any time.

**Comment by rafaellaantoniou** [comment]
I like the idea of the DIN SPEC badge with the different levels, as well as the combination of self-assigned badges + automated badges. 
Other ideas for badges: 
- could relate to community i.e. number of page views, number of contributors etc. 
- something to indicate there is a working prototype which can be built via self-assembly or can be bought 
- a badge of the open source license they are using?

Hope this helps.

**Comment by moedn** [comment]
Thanks for opening this issue and hence the discussion around it :)

Suggestion:

Automatic:
- OSHWA-compliant license (including GPL, CC BY etc.)
  - by checking LICENSE.md
- hardware-specific OSH-license (CERN OHL, TAPR, Solderpad)
  - by checking LICENSE.md
- community-attested according to DIN SPEC 3105-2
  - by identifying an attestation file
- use of standardised metadata
  - by identifying okh.yml or okh.json

Self-awarded:
- compliance with DIN SPEC 3105-1\
  which is without an attestation a bare self-declaration

further ideas for self-awarded badges:
- confidence (sort of the stage of the project)
- funding model (often explains certain dynamics of project and team)\
see [this issue](https://github.com/OPEN-NEXT/OSHI/issues/14) for details

**Comment by penyuan** [comment]
Thanks for the comments, please keep them coming.

Quick note to help myself remember: @moedn mentioned "an ontology for skills of developers in open source projects that may be used to match personal profiles with new projects" that is being developed -> Badges can also be designed around this ontology.
