### ISSUE TITLE
Color code the nodes in commit history networks depending on branch/fork

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#4]

**Comment by jbon** [comment]
tested successfully with args `--user='jbon' --repo='github-mining'`

**Comment by jbon** [comment]
to be validated with other repos. Maybe when we'll have proper network visualisation from #7?

**Comment by penyuan** [comment]
> tested successfully with args `--user='jbon' --repo='github-mining'`
> requires GraphML file editor to check the output. tested with yED Graph Editor

I'll try this on my end, too.

> to be validated with other repos. Maybe when we'll have proper network visualisation from #7?

I will also test against the new demo repo per [issue #3](https://github.com/OPEN-NEXT/wp2.2_dev/issues/3), which is coming up.

**Comment by penyuan** [comment]
Oh, and is this in the [vis-js branch](https://github.com/OPEN-NEXT/wp2.2_dev/tree/vis-js/src)?
