### ISSUE TITLE
Optimize HTML network visualisation and consider alternative libraries

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#5]
- alternative: 1 https://towardsdatascience.com/python-interactive-network-visualization-using-networkx-plotly-and-dash-e44749161ed7
    - alternative: 2 https://graph-tool.skewed.de/
    - alternative 3: vis.js from scratch https://github.com/marcin-kolda/py-graph-vis
    - alternative 4: D3.js

**Comment by penyuan** [comment]
Many thanks to @jbon for input on this.

After recent meetings, we seem to be migrating to using the [Plotly/Dash](https://plotly.com/) family of Python web frameworks for dashboard frontend development. They provide network visualisations so I think this issue is now closable.
