### ISSUE TITLE
Agree on an exception raising style and exception naming convention

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#9]

**Comment by penyuan** [comment]
I've documented some best practices in [this document](https://github.com/OPEN-NEXT/wp2.2_dev/blob/master/docs/code-guide.md) in the `docs` directory.

**Comment by penyuan** [comment]
We discussed this, and decided that we will investigate how easy/feasible it is to implement custom exception handling for our codebase in issue #16.
